import React from 'react'
import Head from 'next/head'
import { Navbar } from './NavBar'

interface LayoutProps {
    children: React.ReactNode
  }

export default function layout({children}: LayoutProps) {
  return (
    <>
      <Head>
        <title>Plactice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </>
  )
}
